'''
bucket sort generated by GPT
'''
from typing import List
from collections import Counter

class Solution:
    def topKFrequent(self, nums: List[int], k: int) -> List[int]:
        cnt = Counter(nums)
        buckets = [[] for _ in range(len(nums) + 1)]  # freq from 0..n

        for num, f in cnt.items():
            buckets[f].append(num)

        ans = []
        for f in range(len(nums), 0, -1):
            for num in buckets[f]:
                ans.append(num)
                if len(ans) == k:
                    return ans
